type Metric {
  id: String!
  deposit_count: Int!
  deposit_amount: Float!
  withdrawal_count: Int!
  withdrawal_amount: Float!
}

type MonthlyMetric {
  id: String!
  deposit_count: Int!
  deposit_amount: Float!
  withdrawal_count: Int!
  withdrawal_amount: Float!
  month: Int!
  year: Int!
}

type DailyMetric {
  id: String!
  deposit_count: Int!
  deposit_amount: Float!
  withdrawal_count: Int!
  withdrawal_amount: Float!
  day: Int!
  month: Int!
  year: Int!
}
